-- Create TRADES Table for Persistent Trade Management
-- Allows PositionManager to recover SL/TP for Limit Orders
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    symbol TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('BUY', 'SELL', 'buy', 'sell')),
    entry_price NUMERIC,
    amount NUMERIC,
    leverage INT DEFAULT 1,
    tp_price NUMERIC,
    sl_price NUMERIC,
    status TEXT DEFAULT 'OPEN', -- OPEN, FILLED, CLOSED, CANCELLED
    order_type TEXT DEFAULT 'MARKET',
    order_id TEXT, -- Exchange Order ID
    meta JSONB DEFAULT '{}'::jsonb, -- Store SMC context, setup details
    pnl NUMERIC,
    close_price NUMERIC,
    closed_at TIMESTAMPTZ
);

-- Index for faster lookup by symbol and status
CREATE INDEX IF NOT EXISTS idx_trades_symbol_status ON trades(symbol, status);

-- Enable RLS
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

-- Allow all access for now (dev mode)
CREATE POLICY "Enable all access for trades" ON trades FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON trades TO anon, authenticated;
